M48
; DRILL file {KiCad (7.0.0)} date Sat Apr  1 17:32:45 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-01T17:32:45+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X109.915Y-98.09
X109.915Y-103.87
T2
X107.0Y-72.0
X107.0Y-114.0
X149.0Y-72.0
X149.0Y-114.0
T0
M30
